/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_shouzhan_design_FsTools */

#ifndef _Included_com_shouzhan_design_FsTools
#define _Included_com_shouzhan_design_FsTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_shouzhan_design_FsTools
 * Method:    getKeyFromJNI
 * Signature: (Ljava/lang/Object;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_shouzhan_design_FsTools_getKeyFromJNI
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
